# service-a.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

###############################
#kubectl exec -it pod-b -- /bin/sh

# Inside the pod-b shell
#curl http://service-a

